version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    reviewers:
      - 'cabch'
      - 'mahdibenromdhane'
      - 'Ramzay'
      - 'ClaudeROSSI'
    versioning-strategy: increase
